from .._legacy_impl import _canonical_officedepot_listing_url, _extract_officedepot_all, _extract_officedepot_listings, _extract_officedepot_multi, _officedepot_card_title, _officedepot_is_product_url, _officedepot_original_price_from_card, _officedepot_price_from_card

